### ISSUE TITLE
Lovely Component! However, is there a way the height can be made dynamics instead of fixed?

### ISSUE THREAD

**Issue by galliumsoft** [pckhoi/react-flop-card#2]
Very useful component.. Am wondering if there is a way to make the height a bit dynamics? I have a material-ui card component inside the flipcard.. however, the card height here doesnt change with the inner component and instead remains fixed. Any way it can be made dynamic, say, through a containerStyle props where you can set it to height: 100%

**Comment by pckhoi** [comment]
Thank you! You can set the width and height yourself easily. Just ignore `width` and `height` props and instead set them like this:

```javascript
<FlipCard ... style={ {
  wrapper: {
    width: 100%,
    height: 100%,
    ...
  },
  front: {
    width: 100%,
    height: 100%,
    ...
  },
  back: {
    width: 100%,
    height: 100%,
    ...
  }
} }/>
```
You can set custom style for wrapper element as well as front and back child like this. Please look at documentation on **style** props. Let me know if you have more questions.

**Comment by pckhoi** [comment]
Oops now that I look at it again, that is not possible. Styles from outside cannot overwrite dimension styles.

**Comment by pckhoi** [comment]
Can you please clarify your use case?

Usually the child component can choose to base dimensions off of parent's, not the other way around. I don't think there are any way to make the flipcard's dimensions to follow it's inner component.

What you can do is to make the inner component dimensions always follow that of flipcard's and change the `width`, `height` props dynamically instead. Of course if you want to set `width` and `height` using units other than `px` then that's another story.

**Comment by galliumsoft** [comment]
True.. .Agree with it generally... but here the usecase is something as follows:
a) I have cards (built in material-ui) where the front part is shown which contains a profile.. and at the back there is more details.. 

b) Now the problem statement.. these cards are of variable size.. largely because of the information it contains.. because its a card, doesnt look good if it were to be put in a scrollable container.. instead, i would prefer that the flipcard adjusts to the size of the card component within it..

**Comment by pckhoi** [comment]
If I understand correctly, you want to change the dimension of the card as it rotate. While it's not impossible to achieve I think it will look quite confusing as you try to combine two animations into one. If you still want to do it then I suggest using `RotateCard` (instead of `FlipCard`) wrapped in `Motion` like in [flip-card.js](https://github.com/pckhoi/react-flop-card/blob/master/src/components/flip-card.js) but instead animate width and height as well.

However I suggest that you separate those 2 animations: rotate then resize or resize then rotate. It will look less confusing and more pleasing. Then you would not need to ask for this kind of feature. Let me know if I misunderstood.

**Comment by galliumsoft** [comment]
Hmm... I guess i didnt explain it clearly.. the back and front card sizes are the same.. what i mean is there are different sized cards.. each has got its different height..

**Comment by pckhoi** [comment]
I'm sorry for misunderstood. Do you want to layout your cards in [masonry style](https://www.google.com.vn/search?q=masonry+layout&safe=off&rlz=1C5CHFA_enVN706VN706&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjw9aunncXWAhVFLo8KHRADDqgQ_AUICigB&biw=1440&bih=656)? Masonry style generally require that you know the dimensions of each card at some points. Some libraries do this for you automatically at some points so it create the impression that the dimensions is not known in advance however I don't think that's the case.

That said I could make the `width` and `height` props optional. That way the parent's dimensions will follow that of the front child and back child. However you still have to set the dimensions for the wrapper yourself (or a library do that for you automatically).

**Comment by galliumsoft** [comment]
Yes... am using Stonecutter library (which is inspired on the masonry style) to arrange the individual cards. It has functions inbuilt to measure the inner cards and align accordingly. In flopcard, Allowing the individual cards to have flexibility on the width and height props will definitely help!  Thanks!

**Comment by pckhoi** [comment]
I have just published version 0.3.0. The major change is that `width` and `height` are now optional. If you leave it unset then you'll have to manipulate width and height with other means. Maybe with `style` prop. And you can also use units other than `px` for width and height by supplying a string instead of number.

I highly doubt that this change will make it "just work" with Stonecutter but at least it'll leave more room for customization.

**Comment by galliumsoft** [comment]
great! Thanks for that... However, the passing of non-numeric values (e.g. 100% or 5em etc) to the width/ height dont seem to be working .... I see what you have done in the code there and seems ok to me.. Not able to put my finger around why the numeric is working but not the non-numeric values.. 
   Any thoughts?

**Comment by pckhoi** [comment]
Closing as it has been opened for too long. Feel free to open a new issue if you need further support.
