### ISSUE TITLE
Mobile Support

### ISSUE THREAD

**Issue by Asher978** [pckhoi/react-flop-card#6]
Thank you for an amazing component. 

Just wondering if there is a mobile support for this component as I would love to integrate this into a project i am working on.

Thanks

**Comment by pckhoi** [comment]
Hi Asher978,

Do you mean mobile web or React native?

**Comment by Asher978** [comment]
Mobile web

**Comment by pckhoi** [comment]
Have you tried this library on mobile web? What issues are you running into? What exactly do you need?

**Comment by Asher978** [comment]
Current behavior: No response on tap gestures while viewing on mobile device. For your reference please see the link for the staged app on heroku

https://staging-branch.herokuapp.com/

**Comment by pckhoi** [comment]
If you want to flip the card on tap then I think the library already support that. Just follow the example in README file but instead of flipping the cards within `onMouseOver` and `onMouseOut`, do it in `onClick`. You obviously might want to detect whether the browser is a mobile browser. You can use [isMobile](https://github.com/kaimallea/isMobile). I believe that's all you should need?
